//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoAcuario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pDulce
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> ph { get; set; }
        public Nullable<int> gh { get; set; }
        public Nullable<int> kh { get; set; }
        public Nullable<decimal> no2 { get; set; }
        public Nullable<decimal> no3 { get; set; }
        public Nullable<decimal> nh4 { get; set; }
        public Nullable<decimal> temperatura { get; set; }
    }
}
