//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoAcuario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pMarino
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> calcio { get; set; }
        public Nullable<int> alcalinidad { get; set; }
        public Nullable<int> salinidad { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public Nullable<decimal> ph { get; set; }
        public Nullable<int> magnesio { get; set; }
        public Nullable<decimal> fosfato { get; set; }
        public Nullable<decimal> amoniaco { get; set; }
        public Nullable<int> potasio { get; set; }
        public Nullable<decimal> silicio { get; set; }
        public Nullable<decimal> nitritos { get; set; }
        public Nullable<decimal> nitratos { get; set; }
        public Nullable<int> estroncio { get; set; }
        public Nullable<decimal> boro { get; set; }
        public Nullable<decimal> hierro { get; set; }
    }
}
